export enum AnomalyType {
  GPS_PRECISION_SPOOFING = 'GPS_PRECISION_SPOOFING',
  GPS_VELOCITY_SPOOFING = 'GPS_VELOCITY_SPOOFING',
  MOCK_LOCATION_DETECTED = 'MOCK_LOCATION_DETECTED',
  OUTSIDE_NIGERIA_BOUNDS = 'OUTSIDE_NIGERIA_BOUNDS',
  CONCURRENT_SESSION_CONFLICT = 'CONCURRENT_SESSION_CONFLICT',
  BOUNDARY_CLUSTERING = 'BOUNDARY_CLUSTERING',
  LAST_MINUTE_PATTERN = 'LAST_MINUTE_PATTERN',
  CLUSTER_IDENTICAL_GPS = 'CLUSTER_IDENTICAL_GPS',
  REPEATED_DAY_PATTERN = 'REPEATED_DAY_PATTERN',
  HOD_AWARENESS_FLAG = 'HOD_AWARENESS_FLAG',
}
