export enum CheckInMethod {
  GPS_DIRECT = 'GPS_DIRECT',
  QR_CODE = 'QR_CODE',
  ALPHANUMERIC_CODE = 'ALPHANUMERIC_CODE',
  FACE_RECOGNITION = 'FACE_RECOGNITION',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
}
