export enum ExcuseStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  APPEAL_SUBMITTED = 'APPEAL_SUBMITTED',
  HOD_APPROVED = 'HOD_APPROVED',
  HOD_REJECTED = 'HOD_REJECTED',
}
