export enum ExcuseReason {
  MEDICAL = 'MEDICAL',
  BEREAVEMENT = 'BEREAVEMENT',
  OFFICIAL_UNIVERSITY_ACTIVITY = 'OFFICIAL_UNIVERSITY_ACTIVITY',
  GOVERNMENT_SUMMONS = 'GOVERNMENT_SUMMONS',
  TRANSPORT_SECURITY_EMERGENCY = 'TRANSPORT_SECURITY_EMERGENCY',
  OTHER = 'OTHER',
}
