export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TicketCategory {
  ATTENDANCE_DISPUTE = 'ATTENDANCE_DISPUTE',
  ACCOUNT_ACCESS = 'ACCOUNT_ACCESS',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  EXCUSE_QUERY = 'EXCUSE_QUERY',
  ELIGIBILITY_QUERY = 'ELIGIBILITY_QUERY',
  OTHER = 'OTHER',
}
